### PR TITLE
Add markdown in comment output

### PR DESCRIPTION
**Pull request by chmac**
Firstly, thanks for this package, saved us a ton of time. :+1: 

Added `{{#markdown}}` around the `{{content}}` output of the comments.

This adds simple newline support to existing comments, and makes the output a little more readable I think. It's also pretty safe, as markdown doesn't allow XSS injections or anything of that nature (as far as I know!).

I've tested the bootstrap version and it renders properly for me. Can't promise there's no bugs in the other two templates, but the changes were pretty small. :-)

### CODE REVIEW

**Comment by chmac** [comment]
Any thoughts on this one @matteodem? It's a pretty significant upgrade for us, there was no newlines in comments previously. We could create a fork and publish it, etc, but we'd rather not pollute atmosphere with many copies of essentially the same package... :-)

**Comment by matteodem** [comment]
Thanks a lot for this feature, I'll have a look at it later today

**Comment by matteodem** [comment]
One thing that I see right now would be that it should be configurable to have markdown in your comments or not, through `Comments.ui.config`. Probably a `useMarkdown` or anything similiar as the key is sufficient for now.

**Comment by chmac** [comment]
@matteodem I thought about that a little. Does it ever make sense to not use markdown? Without markdown text gets rendered as HTML. Except that any actual HTML tags get converted to `&lt;a` etc. So right now, newlines are not possible, and URLs aren't converted into links.

I considered adding a config flag but then thought it through and decided that markdown was a 100% upgrade and there was no reason I could see to not enable it all the time.

However, of course, it's your package! If you think that a flag makes sense given the arguments above, I'll add that and update the PR. One question if so, do you have an opinion about setting the flag to default on or off?

**Comment by matteodem** [comment]
`So right now, newlines are not possible, and URLs aren't converted into links.` That's actually something that should still work even after this PR. 

There are a lot of cases for example when using two `*` or other markdown syntax that might confuse users of this package when using it. Please add a flag.

**Comment by chmac** [comment]
Understood. Does the flag default on or off?

**Comment by matteodem** [comment]
I guess off, but feel free to add some content to the README that this awesome functionality is provided with the flag given.

**Comment by matteodem** [comment]
What's the status of this? I'd love to merge it in

**Comment by chmac** [comment]
Hoping we can get to it in the next 2 weeks or so...

**Comment by matteodem** [comment]
Okay cool :+1:

**Comment by chmac** [comment]
@matteodem One of my colleagues updated the PR. What do you think?

**Comment by matteodem** [comment]
Thanks a lot, I'll have a look later today.

**Comment by matteodem** [comment]
Thank you for the effort, we'll release a new version soon.

**Pull request merged**
